### ISSUE TITLE
Is bayes suitable for bank transaction categorisation?

### ISSUE THREAD

**Issue by pamtbaau** [winkjs/wink-naive-bayes-text-classifier#13]
In an app I've written I categorise downloaded banking transactions using manually created rules. I thought ML could be a handy alternative for this...

I have been trying Wink for several days, but haven't been really successful. I always find approx 10% false categories being assigned and only a few 'unknown'. 'Unknown' is acceptable because these can be assigned manually, but false assignments are detrimental when analysing income and spending.

Is Bayes really suitable for this type of classifications?

A possible issue I can think of, is that transactions of a single payee can be assigned to different categories. Eg. a warehouse store has multiple departments and hence multiple categories (clothing, personal health, entertainment...). The store shows the same name in the transactions, but is assigned to different categories.
- So I created a word list of all words that occur in payees with multiple categories. Still too many errors...
- I created a list of payees with multiple categories and leave them out of the learning dataset. No success either...

Any thoughts/suggestions on this?

**Comment by sanjayaksaxena** [comment]
Hi @pamtbaau 

Is it possible to share some reasonable size sample of training data with us and a little more explanation of the specific use case. You may anonymized the data.

We will be delighted to assist you. If you would like to interact via e-mail please use e-mail given at [wink github page](https://github.com/winkjs).

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
Also share the preparatory task and the configuration that you used.

**Comment by pamtbaau** [comment]
@sanjayaksaxena Thanks for your reply. I need some time to anonymise the dataset and get back to you. What is a "reasonable" dataset size to you? I currently use ~1000 rows for learning.

**Comment by sanjayaksaxena** [comment]
A **good representative** labeled data of 500-1000 rows should be sufficient – roughly equal number of rows for each label.

Do share the prep tasks & config as well.

What kind of accuracy you are targeting to achieve?

**Comment by sanjayaksaxena** [comment]
Hi @pamtbaau 

I am closing the issue for now. You can reopen the issue whenever you are able to provide further details.

Best,
Sanjaya

**Comment by pamtbaau** [comment]
Sorry, I should have closed it myself... At the moment I have stopped considering the use of Bayes. 

Having played a few days more with Bayes, I feel the algorithm is doing too much statistics to predict the most likely category, causing too many incorrect categorisations.
- Quite a few accounts can have multiple categories (e.g. a warehouse store). I don't want any category to be predicted in these cases. I prefer to offer the user a shortlist of possible categories to pick from manually.
- New accounts (not in learning set) also seem to be getting a 'most likely' category. Also in these cases I don't want any category being assigned, but rather notify the user that a category must be picked manually.

In the mean time I've experimented with the following home grown categoriser. Roughly it does the following:
- Learning:
  - Tokenise all account names and add tokens to a dictionary of tokens with a list of categories of accounts token occurs in.
  - Remove all tokens with multiple categories.
  - Mark all accounts with multiple categories as ambiguous.
- Prediction
  - Tokenise all accounts and create dictionary of account with list of categories of found tokens.
  - Create list of ambiguous accounts: Ambiguous accounts found during learning plus accounts with tokens with multiple categories.
  - Create list of accounts which have no tokens found during learning stage. These new accounts are not predictable.

The list of ambiguous and new accounts are then presented to the user to manual assign a category for a transaction.

One type of errors I cannot detect and found no solution for: Accounts that are not ambiguous in the learning dataset and become ambiguous in prediction dataset. For example, when I started buying a health insurance (medical expenses) from a company from which I previously only purchased car insurances (car expenses).

By the way, this type of error also occurs using my current implementation of user-defined categorisation rules (based on regex, if-else, and-or) per account...

**Comment by sanjayaksaxena** [comment]
While the problem looks interesting, we are still unable to get enough clarity to be able to suggest an approach. We feel by extracting the **right features** and choosing a **suitable mechanism of categorization**, you should be able to achieve acceptable levels of accuracy.

Feel free to discuss **details with example data** here or over e-mail...
