### ISSUE TITLE
computeOdds between 0 and 1

### ISSUE THREAD

**Issue by monks1975** [winkjs/wink-naive-bayes-text-classifier#19]
Does anyone do any math conversions on computeOdds that they could share? I'm looking for output values between 0 and 1, for using the data in charts and I'm not sure how the base-2 odds would work?

**Comment by rachnachakraborty** [comment]
Hi @monks1975 

We have not been able to understand your exact need.

Here are few facts which may be of help to you:

1. Computing `antilog of base 2` can give you the odds value;
2. `Probability = Odds/(1 + Odds)`

Hope it helps.

Best,
Rachna
