### ISSUE TITLE
"Unknown" error when literally typing in string from the dataset.

### ISSUE THREAD

**Issue by thestonechat** [winkjs/wink-naive-bayes-text-classifier#23]
So yeah title says it all, I have been playing around with wink js and I just basically made a small dataset, which works all fine but on ONE data. so I got like basics right "hello" and "good bye" "how are you" and I have one that is a type of function "what time is it" *again, I was playing around* so all of em work but "how are you" it says "Unknown".
![image](https://user-images.githubusercontent.com/64982639/108878857-16485b00-761a-11eb-9613-0fe6d2827aa1.png)
^^ thats the how are you message.
and here are other ones:
![image](https://user-images.githubusercontent.com/64982639/108879009-3f68eb80-761a-11eb-96a7-8bd88cb8ba69.png)
![image](https://user-images.githubusercontent.com/64982639/108879033-44c63600-761a-11eb-8291-cabb85d8e0f8.png)
![image](https://user-images.githubusercontent.com/64982639/108879054-4b54ad80-761a-11eb-9c36-5a4d45b35ef9.png)
so yeah. can't figure out the reason it just says unkown idk...

**Comment by thestonechat** [comment]
> 
> 
> Thanks for sharing this @ignStonechat!
> 
> Could you help us reproduce this error? Sharing the code that you've written would help us find and debug the issue.

Are you having trouble with it too?

**Comment by rachnachakraborty** [comment]
Hi @ignStonechat,

Since 'how are you' and 'how are you doing'  are using all stop words, thus returns 'unknown' as they are removed from the pattern while matching.

Tried commenting this statement: `nlp.tokens.removeWords` of `nbc.definePrepTasks` it returns the desired intent `"{\"intent\":\"greeting.feeling\",\"answers\":[\"Good, How is it going with you?\"],\"type\":\"text\"}"`

Thanks for exploring and reaching out.

Cheers!
Rachna

**Comment by thestonechat** [comment]
> 
> 
> Hi @ignStonechat,
> 
> Since 'how are you' and 'how are you doing' are using all stop words, thus returns 'unknown' as they are removed from the pattern while matching.
> 
> Tried commenting this statement: `nlp.tokens.removeWords` of `nbc.definePrepTasks` it returns the desired intent `"{\"intent\":\"greeting.feeling\",\"answers\":[\"Good, How is it going with you?\"],\"type\":\"text\"}"`
> 
> Thanks for exploring and reaching out.
> 
> Cheers!
> Rachna

Oh my god! Didn't even relize that! I just tried it with "natural" too and it posed the SAME problem! thank you so much for help u guys are amazing!

**Comment by thestonechat** [comment]
Quick Update: it works 😃 ! Thanks!
